### ISSUE TITLE
3- No se adapta a distintas resoluciones de pantalla

### ISSUE THREAD

**Issue by Piarrot** [1022FSNSANCN02ARED/mercado-liebre#1]
El header no se adapta correctamente en los tamaños de pantalla de tablet en adelante

![image](https://user-images.githubusercontent.com/4323069/210663811-10e30d5c-4164-4e5e-808f-ad5d09fcbc24.png)

```css
@media (min-width:700px){
    nav ul {
       display:none
     }
}
```
